-- CMS owns Operator knowledge/case authorization and lifecycle. Enrichment
-- only receives bounded text for embedding/reranking and never writes here.
CREATE TABLE IF NOT EXISTS operator_knowledge_documents (
 id BIGSERIAL PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE, tenant_id VARCHAR(64) NOT NULL, key VARCHAR(160) NOT NULL, version INTEGER NOT NULL CHECK(version>0), title TEXT NOT NULL, status VARCHAR(24) NOT NULL CHECK(status IN ('reviewed','retired')), required_permissions TEXT[] NOT NULL DEFAULT '{}', space_id CHAR(64) NOT NULL, source_version VARCHAR(160) NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_until TIMESTAMPTZ, reviewed_by VARCHAR(255) NOT NULL, reviewed_at TIMESTAMPTZ NOT NULL, retired_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(tenant_id,key,version));
CREATE TABLE IF NOT EXISTS operator_knowledge_chunks (id BIGSERIAL PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES operator_knowledge_documents(id) ON DELETE CASCADE, tenant_id VARCHAR(64) NOT NULL, ordinal INTEGER NOT NULL, content TEXT NOT NULL, embedding vector(1024) NOT NULL, space_id CHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(document_id,ordinal));
CREATE TABLE IF NOT EXISTS operator_resolved_cases (
 id BIGSERIAL PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE, tenant_id VARCHAR(64) NOT NULL, key VARCHAR(160) NOT NULL, version INTEGER NOT NULL CHECK(version>0), title TEXT NOT NULL, status VARCHAR(24) NOT NULL CHECK(status IN ('reviewed','retired')), required_permissions TEXT[] NOT NULL DEFAULT '{}', space_id CHAR(64) NOT NULL, provenance TEXT NOT NULL, valid_from TIMESTAMPTZ NOT NULL, valid_until TIMESTAMPTZ, reviewed_by VARCHAR(255) NOT NULL, reviewed_at TIMESTAMPTZ NOT NULL, retired_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(tenant_id,key,version));
CREATE TABLE IF NOT EXISTS operator_resolved_case_chunks (id BIGSERIAL PRIMARY KEY, case_id BIGINT NOT NULL REFERENCES operator_resolved_cases(id) ON DELETE CASCADE, tenant_id VARCHAR(64) NOT NULL, ordinal INTEGER NOT NULL, content TEXT NOT NULL, embedding vector(1024) NOT NULL, space_id CHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(case_id,ordinal));
CREATE INDEX IF NOT EXISTS idx_operator_knowledge_chunks_scope ON operator_knowledge_chunks(tenant_id,space_id);
CREATE INDEX IF NOT EXISTS idx_operator_case_chunks_scope ON operator_resolved_case_chunks(tenant_id,space_id);
